### ISSUE TITLE
Minimum GPU needed?

### ISSUE THREAD

**Issue by motowntalent** [JackismyShephard/ultimate-rvc#118]
Can you add the minimum GPU needed to the readme so that users can determine whether to use the local or Colab version?
Also, is a Huggingface option available?

**Comment by JackismyShephard** [comment]
Hi @motowntalent ! What do you mean by minimum GPU? I have a Nvidia 3080 and it is definitely faster locally than through colab. I cannot say whether or not that is the case for other people as inference on speed depends on many other factors, like throttling etc.. Moreover I dont have any other local GPUs I can compare with.

By huggingface version do you mean to ask whether this project is hosted permanently on huggingface? That is not the case. I see no reason to do that as it will only be hosted on CPU, which is not useful.

**Comment by motowntalent** [comment]
Just asking because the details say "For those without a powerful enough NVIDIA GPU". Some AI projects require A100s and such to perform reasonably. 3080 is reasonable. A lot of users will be able to use it. 👍
Huggingface is just another option similar to Colab where you could host it that's all. 
Thanks.

**Comment by JackismyShephard** [comment]
@motowntalent Hosting it on Huggingface is easy but I am not going to be paying for compute on that platform :yum: . Hence, I think colab makes more sense as you at least can get some free GPU acceleration there.

**Comment by motowntalent** [comment]
I hear you. But you can host it for free. Then people can duplicate it on there own with a GPU Space. You can also apply for a free Community Grant to host it on Zero-Spaces. 
Anyway, just think it will help more people to find and use this. 
Cheers.
