### ISSUE TITLE
How to use Python package?

### ISSUE THREAD

**Issue by SpyC0der77** [JackismyShephard/ultimate-rvc#121]
I tried using the python package but I can't figure out how. Can you add some documentation or just give me an example program?

**Comment by JackismyShephard** [comment]
Hi @SpyC0der77 !

There is a section on how to install and use the PyPI package in the README of this project. Is there something you feel is missing there?

In short the PyPI package exposes two commands: `urvc` and `urvc-web`. you can run `urvc-web` to start an instance of the Ultimate RVC web application locally. `urvc` starts the Ultimate RVC CLI application. Currently there is only one command implemented, namely one for running the full song cover generation pipeline. You can run it like `urvc song-cover run-pipeline [SOURCE] [VOICE_MODEL] [OPTIONS]`. For more information on either command you can supply the option `--help`

**Comment by SpyC0der77** [comment]
Run that in the terminal?

**Comment by JackismyShephard** [comment]
Yes, all commands are run in the terminal 😄

**Comment by JackismyShephard** [comment]
@SpyC0der77 Going to close this now but you are welcome to raise another issue if you have more problems.
