### ISSUE TITLE
noice when using tts voice 

### ISSUE THREAD

**Issue by soit-k** [JackismyShephard/ultimate-rvc#130]
Whenever I use it with TTS voices like the male voice "Russell," the "noice" is too loud. Any fix?

**Comment by JackismyShephard** [comment]
Hi @soit-k. Rvc-based tts is still not merged to the main branch. Did you checkout the development branch? That branch is still a work in progress.

**Comment by JackismyShephard** [comment]
@soit-k Did you fix this ? otherwise I will close this issue.
