### ISSUE TITLE
[Issue with new version] Not able to create instrumenal version, old version was working fine

### ISSUE THREAD

**Issue by nitinmukesh** [JackismyShephard/ultimate-rvc#66]
Hello,

I did a quick check "Multi-step generation"

Step 1: vocals/instrumentals separation

Vocals is fine and instrumentals include vocals too. I can confirm it was working fine yesterday before the update. 

Input song (Copyright free)
https://www.youtube.com/watch?v=7UmBGMktAoI

Vocal and Instrumental
https://drive.google.com/file/d/13kscfz84qn9o4Jkaf0ByyP4x8Bttr-ha/view?usp=sharing

**Comment by JackismyShephard** [comment]
Is the problem that the the instrumentals include traces of the vocals?

**Comment by JackismyShephard** [comment]
@nitinmukesh Also, I would be curious to know your general thoughts on the quality of the audio output in the new version of ultimate-rvc. I was debating alot whether or not to do this upgrade, as some things are indeed worse than before. If the output audio quality is sufficiently bad I might revert to the old version, but that would have to be a very serious issue, as there are many other benefits with the new version of ultimate-rvc

**Comment by nitinmukesh** [comment]
I guess the issue of vocals in instrumental is because earlier MDX models were used and it was working fine. Now only RVC models are used. Please correct me if I am wrong. I would request to make it work like earlier as it is one important feature of having only instrumental version without vocals. I loved that feature.

Audio quality, even though I have not done much comparison but it was slightly better earlier. I checked with the same song earlier and with new version. Can't say it is noticeable.

**Comment by JackismyShephard** [comment]
@nitinmukesh You are wrong about only RVC being used now. MDXNet models are still being used. their default settings are just a bit different. The problem with vocal residue in extracted instrumentals was also present before the update. It may be that the problem is bigger now. Did you test with many different songs? As i mentioned before, the new models with their current settings seems to improve quality of vocals but not instrumentals. In general, it seems difficult to strike a perfect balance, as you are always compromising on quality somewhere. 

I really appreciate all your testing. If you continue to experience problems with instrumentals, please let me know.

**Comment by nitinmukesh** [comment]
No problem. I am ready to test any new features.

I still don't find any MDXNet models in new version

<img width="557" alt="image" src="https://github.com/user-attachments/assets/a0f29135-4146-493c-a3e9-69845cf93e7a">

**Comment by JackismyShephard** [comment]
the mdxnet models are stored in `models/audio_separator/` :blush:

**Comment by nitinmukesh** [comment]
> the mdxnet models are stored in `models/audio_separator/` They will be downloaded on the fly as needed 😊

Got it, thanks.

Sorry for asking so many questions and I hope this is the last one. Is there any way to get instrumental version like before i.e. without vocals.

**Comment by JackismyShephard** [comment]
No worries, your questions are appreciated.

Currently you can't do anything to get better instrumentals stems. But, if the quality of the instrumentals stems you generate in general is not good enough (bleed through of vocals) and that is something important to you (and potentially other users), then I will look into improving the performance. First of all, I will try to fiddle around with some settings. If that does not improve things, then I might revert the app to the old version.

**Comment by nitinmukesh** [comment]
Appreciate you looking into this. It's not the quality, quality is good. It's just the instrumental version should not have vocals.

Thank you.

**Comment by nitinmukesh** [comment]
@JackismyShephard 

I guess I was wrong about instrument version not having vocals. I just tried original AIICoverGen and it have vocals too.

Sorry for wasting your time.
