### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by medicenjona1** [JackismyShephard/ultimate-rvc#72]
I created a simple Google Colab that uses Ngrok to obtain a URL. It's a basic setup. Repository with the Colab: https://github.com/medicenjona1/ultimate-rvc/

**Comment by JackismyShephard** [comment]
@medicenjona1 that is great! I was considering implementing one myself. If you want, you could try and make a pull request and I will have a look at the notebook.

**Comment by SpyC0der77** [comment]
can you make this also have the option for hugging face?

**Comment by SpyC0der77** [comment]
it doesn't work for me

**Comment by JackismyShephard** [comment]
The colab notebook does not work for you now? What exactly are you experiencing?

**Comment by JackismyShephard** [comment]
It is working on my end

**Comment by SpyC0der77** [comment]
on the medicenjonas colab, it deploys it, but then it shows me the ui and says connection errored out

**Comment by JackismyShephard** [comment]
Ahh ok, but why not just use the official Ultimate RVC colab notebook?

**Comment by SpyC0der77** [comment]
cuz the notebook doesn't deploy to a website

**Comment by medicenjona1** [comment]
> cuz the notebook doesn't deploy to a website

https://colab.research.google.com/github/hinabl/AICoverGen-Colab/blob/main/Hina_Mod_AICoverGen_colab.ipynb
