### ISSUE TITLE
information and advice 

### ISSUE THREAD

**Issue by blane187gt** [JackismyShephard/ultimate-rvc#94]
yt_dlp now support from many sites, check the complete list [here](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) @JackismyShephard

**Comment by JackismyShephard** [comment]
I appreciate the info 💪 . I might have a look at this later and see how it works with the current song cover generation pipeline 😄

**Comment by JackismyShephard** [comment]
What is the exact problem with the `requirements.txt`  file? Are you having problems running one of the `./urvc`  commands?

**Comment by JackismyShephard** [comment]
Thank you for informing me. I will have a look at that soon

**Comment by JackismyShephard** [comment]
@blane187gt I just tried running the notebook and everything works for me. If you are still having issues, I probably will need more information on your current setup as well as detailed error logs to solve those issues.
