### ISSUE TITLE
running this program doesn't work and doesn't do much

### ISSUE THREAD

**Issue by arch2kx** [JackismyShephard/ultimate-rvc#98]
Starting Ultimate RVC
INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Successfully loaded faiss with AVX2 support.
DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 6.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 6 extension.
Traceback (most recent call last):
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError: Error in dlopen: /home/a2nc7n/.asdf/installs/python/anaconda3-2023.09-0/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libvpl.so.2)
Exception raised from DynamicLibrary at ../aten/src/ATen/DynamicLibrary.cpp:38 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f5539ea5617 in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x109a13c (0x7f54f0c9a13c in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torchaudio::find_avutil(char const*) + 0x1a (0x7f5496c394ca in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so)
frame #3: <unknown function> + 0x6f8e (0x7f550ae20f8e in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/lib/_torchaudio.so)
frame #4: <unknown function> + 0x11847 (0x7f550ae2b847 in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/lib/_torchaudio.so)
frame #5: ./dependencies/.venv/bin/python() [0x525f07]
frame #6: _PyObject_MakeTpCall + 0x254 (0x502d54 in ./dependencies/.venv/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x755 (0x50f025 in ./dependencies/.venv/bin/python)
frame #8: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #9: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #10: ./dependencies/.venv/bin/python() [0x5e1623]
frame #11: ./dependencies/.venv/bin/python() [0x51c107]
frame #12: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #13: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #14: ./dependencies/.venv/bin/python() [0x524a53]
frame #15: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #16: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #17: ./dependencies/.venv/bin/python() [0x566270]
frame #18: ./dependencies/.venv/bin/python() [0x51c107]
frame #19: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #20: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #21: ./dependencies/.venv/bin/python() [0x524a53]
frame #22: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #23: PyImport_ImportModuleLevelObject + 0x966 (0x553066 in ./dependencies/.venv/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #25: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #26: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #27: ./dependencies/.venv/bin/python() [0x5e1623]
frame #28: ./dependencies/.venv/bin/python() [0x51c107]
frame #29: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #30: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #31: ./dependencies/.venv/bin/python() [0x524a53]
frame #32: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #33: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #35: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #36: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #37: ./dependencies/.venv/bin/python() [0x5e1623]
frame #38: ./dependencies/.venv/bin/python() [0x51c107]
frame #39: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #40: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #41: ./dependencies/.venv/bin/python() [0x524a53]
frame #42: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #43: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #44: ./dependencies/.venv/bin/python() [0x566270]
frame #45: ./dependencies/.venv/bin/python() [0x51c107]
frame #46: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #47: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #48: ./dependencies/.venv/bin/python() [0x524a53]
frame #49: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #50: PyImport_ImportModuleLevelObject + 0x966 (0x553066 in ./dependencies/.venv/bin/python)
frame #51: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #52: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #53: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #54: ./dependencies/.venv/bin/python() [0x5e1623]
frame #55: ./dependencies/.venv/bin/python() [0x51c107]
frame #56: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #57: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #58: ./dependencies/.venv/bin/python() [0x524a53]
frame #59: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #60: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #61: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #62: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #63: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)

DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 5.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 5 extension.
Traceback (most recent call last):
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError: Error in dlopen: libavutil.so.57: cannot open shared object file: No such file or directory
Exception raised from DynamicLibrary at ../aten/src/ATen/DynamicLibrary.cpp:38 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f5539ea5617 in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x109a13c (0x7f54f0c9a13c in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torchaudio::find_avutil(char const*) + 0x1a (0x7f5496c394ca in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so)
frame #3: <unknown function> + 0x6f8e (0x7f550ae20f8e in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/lib/_torchaudio.so)
frame #4: <unknown function> + 0x11847 (0x7f550ae2b847 in /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/lib/_torchaudio.so)
frame #5: ./dependencies/.venv/bin/python() [0x525f07]
frame #6: _PyObject_MakeTpCall + 0x254 (0x502d54 in ./dependencies/.venv/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x755 (0x50f025 in ./dependencies/.venv/bin/python)
frame #8: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #9: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #10: ./dependencies/.venv/bin/python() [0x5e1623]
frame #11: ./dependencies/.venv/bin/python() [0x51c107]
frame #12: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #13: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #14: ./dependencies/.venv/bin/python() [0x524a53]
frame #15: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #16: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #17: ./dependencies/.venv/bin/python() [0x566270]
frame #18: ./dependencies/.venv/bin/python() [0x51c107]
frame #19: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #20: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #21: ./dependencies/.venv/bin/python() [0x524a53]
frame #22: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #23: PyImport_ImportModuleLevelObject + 0x966 (0x553066 in ./dependencies/.venv/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #25: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #26: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #27: ./dependencies/.venv/bin/python() [0x5e1623]
frame #28: ./dependencies/.venv/bin/python() [0x51c107]
frame #29: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #30: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #31: ./dependencies/.venv/bin/python() [0x524a53]
frame #32: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #33: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #35: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #36: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #37: ./dependencies/.venv/bin/python() [0x5e1623]
frame #38: ./dependencies/.venv/bin/python() [0x51c107]
frame #39: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #40: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #41: ./dependencies/.venv/bin/python() [0x524a53]
frame #42: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #43: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #44: ./dependencies/.venv/bin/python() [0x566270]
frame #45: ./dependencies/.venv/bin/python() [0x51c107]
frame #46: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #47: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #48: ./dependencies/.venv/bin/python() [0x524a53]
frame #49: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #50: PyImport_ImportModuleLevelObject + 0x966 (0x553066 in ./dependencies/.venv/bin/python)
frame #51: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #52: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #53: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)
frame #54: ./dependencies/.venv/bin/python() [0x5e1623]
frame #55: ./dependencies/.venv/bin/python() [0x51c107]
frame #56: _PyEval_EvalFrameDefault + 0x8eb7 (0x517787 in ./dependencies/.venv/bin/python)
frame #57: _PyFunction_Vectorcall + 0x173 (0x535103 in ./dependencies/.venv/bin/python)
frame #58: ./dependencies/.venv/bin/python() [0x524a53]
frame #59: PyObject_CallMethodObjArgs + 0x11c (0x553a4c in ./dependencies/.venv/bin/python)
frame #60: PyImport_ImportModuleLevelObject + 0x74c (0x552e4c in ./dependencies/.venv/bin/python)
frame #61: _PyEval_EvalFrameDefault + 0x62e4 (0x514bb4 in ./dependencies/.venv/bin/python)
frame #62: ./dependencies/.venv/bin/python() [0x5c82ce]
frame #63: PyEval_EvalCode + 0x9f (0x5c79cf in ./dependencies/.venv/bin/python)

DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 4.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 4 extension.
Traceback (most recent call last):
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 115, in _find_versionsed_ffmpeg_extension
    _load_lib(library)
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/home/a2nc7n/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/a2nc7n/.asdf/installs/python/anaconda3-2023.09-0/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libsrt.so.1.5)
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 89, in <module>
    _FFMPEG_EXT = _init_ffmpeg()
                  ^^^^^^^^^^^^^^
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 162, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers, show_error)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 132, in _find_ffmpeg_extension
    raise ImportError(f"Failed to intialize FFmpeg extension. Tried versions: {ffmpeg_vers}")
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4']
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:httpx:load_verify_locations cafile='/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpx:load_verify_locations cafile='/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='api.gradio.app' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.started host='checkip.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:matplotlib:matplotlib data path: /home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/a2nc7n/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f5496514d90>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f5496a8e570> server_hostname='checkip.amazonaws.com' timeout=3
DEBUG:matplotlib:CACHEDIR=/home/a2nc7n/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/a2nc7n/.cache/matplotlib/fontlist-v390.json
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f54969cfbd0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f5496a8e3c0> server_hostname='api.gradio.app' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f5496514ad0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'', [(b'Date', b'Sun, 22 Sep 2024 07:47:55 GMT'), (b'Content-Type', b'text/plain;charset=UTF-8'), (b'Content-Length', b'13'), (b'Connection', b'keep-alive'), (b'Server', b'nginx'), (b'Vary', b'Origin'), (b'Vary', b'Access-Control-Request-Method'), (b'Vary', b'Access-Control-Request-Headers')])
INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f5494d41c90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /api/telemetry/gradio/initiated HTTP/11" 200 0
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Sun, 22 Sep 2024 07:47:56 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'21'), (b'Connection', b'keep-alive'), (b'Server', b'nginx/1.18.0'), (b'Access-Control-Allow-Origin', b'*')])
INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:asyncio:Using selector: EpollSelector
Running on local URL:  http://127.0.0.1:7860
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/home/a2nc7n/codes/ultimate-rvc/dependencies/.venv/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='127.0.0.1' port=7860 local_address=None timeout=None socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f54a324b190>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'date', b'Sun, 22 Sep 2024 07:47:56 GMT'), (b'server', b'uvicorn'), (b'content-length', b'4'), (b'content-type', b'application/json')])
INFO:httpx:HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpx:load_ssl_context verify=False cert=None trust_env=True http2=False
DEBUG:httpcore.connection:connect_tcp.started host='127.0.0.1' port=7860 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f54a3176e90>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'date', b'Sun, 22 Sep 2024 07:47:56 GMT'), (b'server', b'uvicorn'), (b'content-length', b'422933'), (b'content-type', b'text/html; charset=utf-8')])
INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete

To create a public link, set `share=True` in `launch()`.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /api/telemetry/gradio/launched HTTP/11" 200 0

**Comment by JackismyShephard** [comment]
@arch2kx Sorry I didnt see your issue before now. I gather you figured out which link to press? By the way I have implemented a much nicer logging system where all DEBUG and INFO level logging messages go to a file and not the console. This should make using the colab notebook quite easier 😄
